In [2]:
import pandas as pd

In [5]:
df_2021 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2021년.csv",  encoding='cp949', header=15)
df_2022 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)
df_2023 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2023년.csv",  encoding='cp949', header=15)
df_2024 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2024년.csv",  encoding='cp949', header=15)

C:\Users\rmagm\AppData\Local\Temp\ipykernel_11716\1231440484.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)
C:\Users\rmagm\AppData\Local\Temp\ipykernel_11716\1231440484.py:3: DtypeWarning: Columns (9,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2023년.csv",  encoding='cp949', header=15)
C:\Users\rmagm\AppData\Local\Temp\ipykernel_11716\1231440484.py:4: DtypeWarning: Columns (9,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2024년.csv",  encoding='cp949', header=15)

In [6]:
df_deal2021 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2021년.csv",  encoding='cp949', header=15)
df_deal2022 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)
df_deal2023 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2023년.csv",  encoding='cp949', header=15)
df_deal2024 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2024년.csv",  encoding='cp949', header=15)

C:\Users\rmagm\AppData\Local\Temp\ipykernel_11716\1277501512.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_deal2022 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)
C:\Users\rmagm\AppData\Local\Temp\ipykernel_11716\1277501512.py:3: DtypeWarning: Columns (9,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_deal2023 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2023년.csv",  encoding='cp949', header=15)
C:\Users\rmagm\AppData\Local\Temp\ipykernel_11716\1277501512.py:4: DtypeWarning: Columns (9,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_deal2024 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2024년.csv",  encoding='cp949', header=15)

In [16]:
print("2021년 단독 다가구 전월세")
display(df_2021)
print("2022년 단독 다가구 전월세")
display(df_2022)
print("2023년 단독 다가구 전월세")
display(df_2023)
print("2024년 단독 다가구 전월세")
display(df_2024)

2021년 단독 다가구 전월세

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 용산구 이태원동,3**,12m미만,30.00,월세,202112,31,500,55,1996.0,녹사평대로40나길,-,-,-,NaN,NaN,단독다가구
1,2,서울특별시 종로구 평창동,5**,8m미만,182.54,전세,202112,31,"70,000",0,2016.0,평창4길,202201~202401,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 용답동,8*,8m미만,28.00,월세,202112,31,"1,000",30,1990.0,용답29길,-,-,-,NaN,NaN,단독다가구
3,4,서울특별시 용산구 청파동2가,6*,8m미만,18.00,월세,202112,31,"1,000",45,1977.0,청파로47길,202202~202302,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 성동구 마장동,3**,8m미만,18.00,전세,202112,31,"13,000",0,2018.0,마조로14길,202201~202401,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165983,165984,서울특별시 동대문구 회기동,5*,8m미만,40.33,월세,202101,1,"1,000",60,2001.0,회기로25길,-,-,-,NaN,NaN,단독다가구
165984,165985,서울특별시 중랑구 상봉동,3**,8m미만,39.83,월세,202101,1,500,35,1993.0,봉화산로30길,-,-,-,NaN,NaN,단독다가구
165985,165986,서울특별시 중랑구 중화동,2**,8m미만,39.66,월세,202101,1,"1,000",30,1995.0,동일로144가길,202101~202212,-,-,NaN,NaN,단독다가구
165986,165987,서울특별시 중랑구 중화동,3**,8m미만,56.49,전세,202101,1,"17,000",0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구
165987,165988,서울특별시 중랑구 중화동,3**,8m미만,56.49,전세,202101,1,"17,000",0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구

2022년 단독 다가구 전월세

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 용산구 후암동,1**,8m미만,15.90,월세,202212,31,500,40,NaN,두텁바위로1나길,202212~202412,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 종로구 명륜1가,3*,8m미만,18.15,월세,202212,31,"1,000",60,2010.0,혜화로5길,202301~202501,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 행당동,3*,8m미만,15.00,월세,202212,31,"4,000",40,1964.0,살곶이4길,202301~202501,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 중구 장충동2가,1**,8m미만,37.47,전세,202212,31,"18,500",0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 종로구 명륜3가,*,8m미만,42.00,전세,202212,31,"8,000",0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178461,178462,서울특별시 영등포구 당산동1가,2**,8m미만,47.88,월세,202201,1,"2,500",20,1989.0,당산로12길,-,-,-,NaN,NaN,단독다가구
178462,178463,서울특별시 금천구 독산동,1**,12m미만,43.80,월세,202201,1,"2,000",70,2002.0,시흥대로136길,202201~202401,신규,-,NaN,NaN,단독다가구
178463,178464,서울특별시 구로구 개봉동,9*,8m미만,132.00,전세,202201,1,"15,000",0,1993.0,고척로,202201~202501,갱신,-,"11,000",0.0,단독다가구
178464,178465,서울특별시 금천구 독산동,1***,12m미만,13.20,월세,202201,1,200,20,1983.0,독산로64길,202201~202412,신규,-,NaN,NaN,단독다가구
178465,178466,서울특별시 구로구 고척동,1**,8m미만,69.37,월세,202201,1,"2,500",20,1989.0,고척로,-,-,-,NaN,NaN,단독다가구

2023년 단독 다가구 전월세

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,2**,8m미만,125.86,전세,202312,31,"10,000",0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,1*,8m미만,39.83,전세,202312,31,"9,200",0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 용답동,3*,12m미만,22.00,월세,202312,31,500,35,1993.0,용답25길,202401~202601,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 성동구 성수동1가,7*,12m미만,10.93,월세,202312,31,150,57,NaN,뚝섬로3길,202401~202412,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 용산구 용산동2가,*,8m미만,20.00,월세,202312,31,"1,000",30,1995.0,신흥로25가길,-,-,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154380,154381,서울특별시 구로구 고척동,6*,8m미만,35.00,월세,202301,1,500,27,NaN,안양천로537다길,202401~202601,신규,-,NaN,NaN,단독다가구
154381,154382,서울특별시 금천구 시흥동,8**,8m미만,24.00,월세,202301,1,500,23,1988.0,독산로28길,-,-,-,NaN,NaN,단독다가구
154382,154383,서울특별시 영등포구 당산동1가,1**,12m미만,42.70,전세,202301,1,"28,324",0,1970.0,영등포로29길,202301~202412,신규,-,NaN,NaN,단독다가구
154383,154384,서울특별시 구로구 가리봉동,2*,8m미만,20.00,월세,202301,1,300,35,1991.0,구로동로5길,-,-,-,NaN,NaN,단독다가구
154384,154385,서울특별시 금천구 독산동,9**,8m미만,17.00,월세,202301,1,"3,000",30,NaN,독산로103길,202307~202507,갱신,-,"1,000",34.0,단독다가구

2024년 단독 다가구 전월세

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 중구 황학동,1**,12m미만,24.00,월세,202412,31,400,40,1991.0,마장로3길,202501~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 행당동,3**,8m미만,42.00,전세,202412,31,"14,000",0,1998.0,마조로1길,202501~202701,갱신,-,"13,000",0.0,단독다가구
2,3,서울특별시 성동구 행당동,3**,12m미만,26.00,월세,202412,31,"3,000",70,NaN,행당로11길,202502~202702,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 성동구 옥수동,3**,8m미만,169.30,월세,202412,31,"1,000",80,1991.0,한림말3길,202501~202701,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 용산구 서계동,2**,8m미만,26.45,전세,202412,31,"3,000",0,1944.0,효창원로104라길,202501~202701,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141366,141367,서울특별시 관악구 신림동,1**,8m미만,35.00,월세,202401,1,500,60,1995.0,서림길,202401~202501,신규,-,NaN,NaN,단독다가구
141367,141368,서울특별시 관악구 신림동,1***,12m미만,20.00,월세,202401,1,300,47,NaN,조원로2길,202402~202501,신규,-,NaN,NaN,단독다가구
141368,141369,서울특별시 관악구 신림동,9*,8m미만,16.52,월세,202401,1,500,43,2012.0,신림로54길,202401~202412,신규,-,NaN,NaN,단독다가구
141369,141370,서울특별시 관악구 신림동,1**,12m미만,12.00,월세,202401,1,100,42,1994.0,서림길,202401~202402,신규,-,NaN,NaN,단독다가구
141370,141371,서울특별시 관악구 신림동,4**,-,15.00,월세,202401,1,"5,000",30,NaN,NaN,-,-,-,NaN,NaN,단독다가구

In [17]:
# 단독 다가구 전월세
print("2021년 단독 다가구 전월세")
print(df_2021.info())
print("2022년 단독 다가구 전월세")
print(df_2022.info())
print("2023년 단독 다가구 전월세")
print(df_2023.info())
print("2024년 단독 다가구 전월세")
print(df_2024.info())

2021년 단독 다가구 전월세

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165988 entries, 0 to 165987
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            165988 non-null  int64
 1   시군구           165988 non-null  object
 2   번지            165965 non-null  object
 3   도로조건          165988 non-null  object
 4   계약면적(㎡)       165988 non-null  float64
 5   전월세구분         165988 non-null  object
 6   계약년월          165988 non-null  int64
 7   계약일           165988 non-null  int64
 8   보증금(만원)       165988 non-null  object
 9   월세금(만원)       165988 non-null  int64
 10  건축년도          156134 non-null  float64
 11  도로명           149332 non-null  object
 12  계약기간          165988 non-null  object
 13  계약구분          165988 non-null  object
 14  갱신요구권 사용      165988 non-null  object
 15  종전계약 보증금(만원)  7634 non-null    object
 16  종전계약 월세(만원)   7634 non-null    float64
 17  주택유형          165988 non-null  object
dtypes: float64(3), int64(4), object(11)
memory usage: 22.8+ MB
None
2022년 단독 다가구 전월세
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178466 entries, 0 to 178465
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            178466 non-null  int64
 1   시군구           178466 non-null  object
 2   번지            178452 non-null  object
 3   도로조건          178466 non-null  object
 4   계약면적(㎡)       178466 non-null  float64
 5   전월세구분         178466 non-null  object
 6   계약년월          178466 non-null  int64
 7   계약일           178466 non-null  int64
 8   보증금(만원)       178466 non-null  object
 9   월세금(만원)       178466 non-null  object
 10  건축년도          168541 non-null  float64
 11  도로명           163848 non-null  object
 12  계약기간          178466 non-null  object
 13  계약구분          178466 non-null  object
 14  갱신요구권 사용      178466 non-null  object
 15  종전계약 보증금(만원)  17340 non-null   object
 16  종전계약 월세(만원)   17340 non-null   float64
 17  주택유형          178466 non-null  object
dtypes: float64(3), int64(3), object(12)
memory usage: 24.5+ MB
None
2023년 단독 다가구 전월세
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154385 entries, 0 to 154384
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            154385 non-null  int64
 1   시군구           154385 non-null  object
 2   번지            154374 non-null  object
 3   도로조건          154385 non-null  object
 4   계약면적(㎡)       154385 non-null  float64
 5   전월세구분         154385 non-null  object
 6   계약년월          154385 non-null  int64
 7   계약일           154385 non-null  int64
 8   보증금(만원)       154385 non-null  object
 9   월세금(만원)       154385 non-null  object
 10  건축년도          143431 non-null  float64
 11  도로명           143360 non-null  object
 12  계약기간          154385 non-null  object
 13  계약구분          154385 non-null  object
 14  갱신요구권 사용      154385 non-null  object
 15  종전계약 보증금(만원)  14808 non-null   object
 16  종전계약 월세(만원)   14808 non-null   object
 17  주택유형          154385 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 21.2+ MB
None
2024년 단독 다가구 전월세
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141371 entries, 0 to 141370
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            141371 non-null  int64
 1   시군구           141371 non-null  object
 2   번지            141371 non-null  object
 3   도로조건          141371 non-null  object
 4   계약면적(㎡)       141371 non-null  float64
 5   전월세구분         141371 non-null  object
 6   계약년월          141371 non-null  int64
 7   계약일           141371 non-null  int64
 8   보증금(만원)       141371 non-null  object
 9   월세금(만원)       141371 non-null  object
 10  건축년도          120702 non-null  float64
 11  도로명           140333 non-null  object
 12  계약기간          141371 non-null  object
 13  계약구분          141371 non-null  object
 14  갱신요구권 사용      141371 non-null  object
 15  종전계약 보증금(만원)  14550 non-null   object
 16  종전계약 월세(만원)   14550 non-null   object
 17  주택유형          141371 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 19.4+ MB
None

In [18]:
# 데이터 모든 컬럼 동일함으로 '번지', '도로조건' 컬럼 제거
# '전월세구분'에서 전세만 추출
drop_columns = ['번지','도로조건']

# 컬럼 제거 및 필터링
def filtered_df(df):
    # 1. 번지, 도로 저건 제거
    df_filtered = df.drop(columns = drop_columns, errors = 'ignore')

    # 2. 전월세구분 '전세'인 행만 추출
    df_filtered = df_filtered[df_filtered['전월세구분'] == '전세']

    return df_filtered.reset_index(drop = True)


# 3. 각 연도별 데이터셋 처리
df_2021_cleaned = filtered_df(df_2021)
df_2022_cleaned = filtered_df(df_2022)
df_2023_cleaned = filtered_df(df_2023)
df_2024_cleaned = filtered_df(df_2024)

print("2021년 단독 다가구 전세")
display(df_2021_cleaned)

print("2022년 단독 다가구 전세")
display(df_2022_cleaned)

print("2023년 단독 다가구 전세")
display(df_2023_cleaned)

print("2024년 단독 다가구 전세")
display(df_2024_cleaned)

2021년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 종로구 평창동,182.54,전세,202112,31,"70,000",0,2016.0,평창4길,202201~202401,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 성동구 마장동,18.00,전세,202112,31,"13,000",0,2018.0,마조로14길,202201~202401,신규,-,NaN,NaN,단독다가구
2,6,서울특별시 성동구 마장동,19.00,전세,202112,31,"10,000",0,1992.0,마조로12길,202202~202402,신규,-,NaN,NaN,단독다가구
3,7,서울특별시 용산구 이태원동,36.13,전세,202112,31,"25,000",0,1991.0,NaN,-,-,-,NaN,NaN,단독다가구
4,9,서울특별시 용산구 이태원동,36.13,전세,202112,31,"25,000",0,1991.0,이태원로16길,202202~202402,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65780,165975,서울특별시 금천구 독산동,54.00,전세,202101,1,"8,000",0,1991.0,독산로58가길,-,-,-,NaN,NaN,단독다가구
65781,165976,서울특별시 영등포구 신길동,23.00,전세,202101,1,"10,000",0,2017.0,도림로,-,-,-,NaN,NaN,단독다가구
65782,165978,서울특별시 중랑구 면목동,67.08,전세,202101,1,"8,500",0,1990.0,용마산로94길,-,-,-,NaN,NaN,단독다가구
65783,165987,서울특별시 중랑구 중화동,56.49,전세,202101,1,"17,000",0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구
65784,165988,서울특별시 중랑구 중화동,56.49,전세,202101,1,"17,000",0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구

2022년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,4,서울특별시 중구 장충동2가,37.47,전세,202212,31,"18,500",0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 종로구 명륜3가,42.00,전세,202212,31,"8,000",0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구
2,11,서울특별시 용산구 후암동,21.02,전세,202212,31,"6,300",0,1960.0,신흥로36길,202302~202502,갱신,사용,"6,000",0.0,단독다가구
3,19,서울특별시 용산구 보광동,36.29,전세,202212,31,"11,500",0,1995.0,우사단로4라길,202301~202501,신규,-,NaN,NaN,단독다가구
4,21,서울특별시 용산구 청파동2가,12.24,전세,202212,31,"7,000",0,1934.0,NaN,-,-,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55524,178457,서울특별시 금천구 가산동,56.62,전세,202201,1,"10,000",0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55525,178458,서울특별시 영등포구 당산동1가,16.50,전세,202201,1,"6,000",0,2015.0,당산로20길,-,-,-,NaN,NaN,단독다가구
55526,178459,서울특별시 금천구 가산동,56.62,전세,202201,1,"10,000",0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55527,178460,서울특별시 구로구 구로동,30.00,전세,202201,1,"8,000",0,2007.0,구로중앙로12길,202203~202403,신규,-,NaN,NaN,단독다가구
55528,178464,서울특별시 구로구 개봉동,132.00,전세,202201,1,"15,000",0,1993.0,고척로,202201~202501,갱신,-,"11,000",0.0,단독다가구

2023년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,125.86,전세,202312,31,"10,000",0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,39.83,전세,202312,31,"9,200",0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,9,서울특별시 광진구 구의동,21.00,전세,202312,31,"12,000",0,2001.0,아차산로49길,202402~202602,신규,-,NaN,NaN,단독다가구
3,12,서울특별시 중랑구 망우동,61.60,전세,202312,31,"14,600",0,2002.0,봉우재로53길,-,-,-,NaN,NaN,단독다가구
4,30,서울특별시 영등포구 대림동,26.00,전세,202312,31,"6,500",0,2010.0,도림로52길,202401~202601,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41231,154353,서울특별시 서대문구 홍제동,28.00,전세,202301,1,"15,600",0,NaN,NaN,-,-,-,NaN,NaN,단독다가구
41232,154359,서울특별시 성북구 하월곡동,16.00,전세,202301,1,"4,500",0,2013.0,월곡로18가길,-,-,-,NaN,NaN,단독다가구
41233,154368,서울특별시 동작구 신대방동,24.00,전세,202301,1,"3,500",0,1970.0,신대방6길,-,-,-,NaN,NaN,단독다가구
41234,154373,서울특별시 금천구 독산동,37.65,전세,202301,1,"9,000",0,1993.0,시흥대로90길,-,-,-,NaN,NaN,단독다가구
41235,154383,서울특별시 영등포구 당산동1가,42.70,전세,202301,1,"28,324",0,1970.0,영등포로29길,202301~202412,신규,-,NaN,NaN,단독다가구

2024년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 성동구 행당동,42.00,전세,202412,31,"14,000",0,1998.0,마조로1길,202501~202701,갱신,-,"13,000",0.0,단독다가구
1,5,서울특별시 용산구 서계동,26.45,전세,202412,31,"3,000",0,1944.0,효창원로104라길,202501~202701,신규,-,NaN,NaN,단독다가구
2,12,서울특별시 용산구 용산동2가,61.17,전세,202412,31,"25,000",0,1994.0,신흥로25가길,202502~202702,신규,-,NaN,NaN,단독다가구
3,19,서울특별시 광진구 중곡동,40.80,전세,202412,31,"11,000",0,1990.0,능동로43길,202502~202702,신규,-,NaN,NaN,단독다가구
4,22,서울특별시 성동구 성수동2가,50.00,전세,202412,31,"16,000",0,1995.0,성덕정길,202502~202702,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32629,141332,서울특별시 중랑구 망우동,36.00,전세,202401,1,"4,000",0,NaN,용마산로120길,202401~202812,신규,-,NaN,NaN,단독다가구
32630,141338,서울특별시 동작구 노량진동,50.00,전세,202401,1,"15,000",0,1970.0,장승배기로18가길,202401~202412,신규,-,NaN,NaN,단독다가구
32631,141349,서울특별시 서대문구 창천동,20.00,전세,202401,1,"10,000",0,2001.0,신촌로7길,202404~202602,신규,-,NaN,NaN,단독다가구
32632,141353,서울특별시 서대문구 남가좌동,18.00,전세,202401,1,"7,000",0,2017.0,증가로8길,202402~202501,신규,-,NaN,NaN,단독다가구
32633,141363,서울특별시 노원구 하계동,50.00,전세,202401,1,"10,000",0,1995.0,공릉로58길,202401~202612,갱신,-,"9,500",0.0,단독다가구

In [19]:
# 각 년도별 컬럼 결측값
display(pd.concat(
    [
        df_2021_cleaned.isnull().sum(),
        df_2022_cleaned.isnull().sum(),
        df_2023_cleaned.isnull().sum(),
        df_2024_cleaned.isnull().sum()
    ],
    axis=1,
    keys=['2021', '2022', '2023', '2024']
).reset_index().rename(columns={'index': 'column'}))

          column   2021   2022   2023   2024
0             NO      0      0      0      0
1            시군구      0      0      0      0
2        계약면적(㎡)      0      0      0      0
3          전월세구분      0      0      0      0
4           계약년월      0      0      0      0
5            계약일      0      0      0      0
6        보증금(만원)      0      0      0      0
7        월세금(만원)      0      0      0      0
8           건축년도   4675   3695   3280   5144
9            도로명   9978   7376   4649    401
10          계약기간      0      0      0      0
11          계약구분      0      0      0      0
12      갱신요구권 사용      0      0      0      0
13  종전계약 보증금(만원)  61029  45655  34146  26209
14   종전계약 월세(만원)  61029  45655  34146  26209
15          주택유형      0      0      0      0

In [ ]:
# 보증금(만원), 월세금(만원) 데이터 타입 int로 변경

# 전처리 함수 정의
def clean_rent_columns(df):
    for col in ['보증금(만원)', '월세금(만원)']:
        df[col] = (
            df[col]
            .astype(str)               # 문자열로 변환
            .str.replace(',', '')      # 쉼표 제거
            .str.strip()               # 공백 제거
        )
        df[col] = pd.to_numeric(df[col], errors='coerce')  # 숫자로 변환, 오류시 NaN
        df[col] = df[col].fillna(0).astype(int)            # NaN은 0으로 대체 후 int
    return df

# 데이터프레임별로 처리
df_2021_cleaned = clean_rent_columns(df_2021_cleaned)
df_2022_cleaned = clean_rent_columns(df_2022_cleaned)
df_2023_cleaned = clean_rent_columns(df_2023_cleaned)
df_2024_cleaned = clean_rent_columns(df_2024_cleaned)

# 결과 확인
print("2021년 단독 다가구 전세")
display(df_2021_cleaned)

print("2022년 단독 다가구 전세")
display(df_2022_cleaned)

print("2023년 단독 다가구 전세")
display(df_2023_cleaned)

print("2024년 단독 다가구 전세")
display(df_2024_cleaned)

2021년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 종로구 평창동,182.54,전세,202112,31,70000,0,2016.0,평창4길,202201~202401,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 성동구 마장동,18.00,전세,202112,31,13000,0,2018.0,마조로14길,202201~202401,신규,-,NaN,NaN,단독다가구
2,6,서울특별시 성동구 마장동,19.00,전세,202112,31,10000,0,1992.0,마조로12길,202202~202402,신규,-,NaN,NaN,단독다가구
3,7,서울특별시 용산구 이태원동,36.13,전세,202112,31,25000,0,1991.0,NaN,-,-,-,NaN,NaN,단독다가구
4,9,서울특별시 용산구 이태원동,36.13,전세,202112,31,25000,0,1991.0,이태원로16길,202202~202402,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65780,165975,서울특별시 금천구 독산동,54.00,전세,202101,1,8000,0,1991.0,독산로58가길,-,-,-,NaN,NaN,단독다가구
65781,165976,서울특별시 영등포구 신길동,23.00,전세,202101,1,10000,0,2017.0,도림로,-,-,-,NaN,NaN,단독다가구
65782,165978,서울특별시 중랑구 면목동,67.08,전세,202101,1,8500,0,1990.0,용마산로94길,-,-,-,NaN,NaN,단독다가구
65783,165987,서울특별시 중랑구 중화동,56.49,전세,202101,1,17000,0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구
65784,165988,서울특별시 중랑구 중화동,56.49,전세,202101,1,17000,0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구

2022년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,4,서울특별시 중구 장충동2가,37.47,전세,202212,31,18500,0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 종로구 명륜3가,42.00,전세,202212,31,8000,0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구
2,11,서울특별시 용산구 후암동,21.02,전세,202212,31,6300,0,1960.0,신흥로36길,202302~202502,갱신,사용,"6,000",0.0,단독다가구
3,19,서울특별시 용산구 보광동,36.29,전세,202212,31,11500,0,1995.0,우사단로4라길,202301~202501,신규,-,NaN,NaN,단독다가구
4,21,서울특별시 용산구 청파동2가,12.24,전세,202212,31,7000,0,1934.0,NaN,-,-,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55524,178457,서울특별시 금천구 가산동,56.62,전세,202201,1,10000,0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55525,178458,서울특별시 영등포구 당산동1가,16.50,전세,202201,1,6000,0,2015.0,당산로20길,-,-,-,NaN,NaN,단독다가구
55526,178459,서울특별시 금천구 가산동,56.62,전세,202201,1,10000,0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55527,178460,서울특별시 구로구 구로동,30.00,전세,202201,1,8000,0,2007.0,구로중앙로12길,202203~202403,신규,-,NaN,NaN,단독다가구
55528,178464,서울특별시 구로구 개봉동,132.00,전세,202201,1,15000,0,1993.0,고척로,202201~202501,갱신,-,"11,000",0.0,단독다가구

2023년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,125.86,전세,202312,31,10000,0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,39.83,전세,202312,31,9200,0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,9,서울특별시 광진구 구의동,21.00,전세,202312,31,12000,0,2001.0,아차산로49길,202402~202602,신규,-,NaN,NaN,단독다가구
3,12,서울특별시 중랑구 망우동,61.60,전세,202312,31,14600,0,2002.0,봉우재로53길,-,-,-,NaN,NaN,단독다가구
4,30,서울특별시 영등포구 대림동,26.00,전세,202312,31,6500,0,2010.0,도림로52길,202401~202601,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41231,154353,서울특별시 서대문구 홍제동,28.00,전세,202301,1,15600,0,NaN,NaN,-,-,-,NaN,NaN,단독다가구
41232,154359,서울특별시 성북구 하월곡동,16.00,전세,202301,1,4500,0,2013.0,월곡로18가길,-,-,-,NaN,NaN,단독다가구
41233,154368,서울특별시 동작구 신대방동,24.00,전세,202301,1,3500,0,1970.0,신대방6길,-,-,-,NaN,NaN,단독다가구
41234,154373,서울특별시 금천구 독산동,37.65,전세,202301,1,9000,0,1993.0,시흥대로90길,-,-,-,NaN,NaN,단독다가구
41235,154383,서울특별시 영등포구 당산동1가,42.70,전세,202301,1,28324,0,1970.0,영등포로29길,202301~202412,신규,-,NaN,NaN,단독다가구

2024년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 성동구 행당동,42.00,전세,202412,31,14000,0,1998.0,마조로1길,202501~202701,갱신,-,"13,000",0.0,단독다가구
1,5,서울특별시 용산구 서계동,26.45,전세,202412,31,3000,0,1944.0,효창원로104라길,202501~202701,신규,-,NaN,NaN,단독다가구
2,12,서울특별시 용산구 용산동2가,61.17,전세,202412,31,25000,0,1994.0,신흥로25가길,202502~202702,신규,-,NaN,NaN,단독다가구
3,19,서울특별시 광진구 중곡동,40.80,전세,202412,31,11000,0,1990.0,능동로43길,202502~202702,신규,-,NaN,NaN,단독다가구
4,22,서울특별시 성동구 성수동2가,50.00,전세,202412,31,16000,0,1995.0,성덕정길,202502~202702,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32629,141332,서울특별시 중랑구 망우동,36.00,전세,202401,1,4000,0,NaN,용마산로120길,202401~202812,신규,-,NaN,NaN,단독다가구
32630,141338,서울특별시 동작구 노량진동,50.00,전세,202401,1,15000,0,1970.0,장승배기로18가길,202401~202412,신규,-,NaN,NaN,단독다가구
32631,141349,서울특별시 서대문구 창천동,20.00,전세,202401,1,10000,0,2001.0,신촌로7길,202404~202602,신규,-,NaN,NaN,단독다가구
32632,141353,서울특별시 서대문구 남가좌동,18.00,전세,202401,1,7000,0,2017.0,증가로8길,202402~202501,신규,-,NaN,NaN,단독다가구
32633,141363,서울특별시 노원구 하계동,50.00,전세,202401,1,10000,0,1995.0,공릉로58길,202401~202612,갱신,-,"9,500",0.0,단독다가구

In [22]:
print("2021년 단독 다가구 전세")
display(df_2021_cleaned['계약구분'].value_counts().reset_index())
print("2022년 단독 다가구 전세")
display(df_2022_cleaned['계약구분'].value_counts().reset_index())
print("2023년 단독 다가구 전세")
display(df_2023_cleaned['계약구분'].value_counts().reset_index())
print("2024년 단독 다가구 전세")
display(df_2024_cleaned['계약구분'].value_counts().reset_index())

2021년 단독 다가구 전세

  계약구분  count
0    -  43441
1   신규  17588
2   갱신   4756

2022년 단독 다가구 전세

  계약구분  count
0   신규  24842
1    -  20813
2   갱신   9874

2023년 단독 다가구 전세

  계약구분  count
0   신규  21359
1    -  12787
2   갱신   7090

2024년 단독 다가구 전세

  계약구분  count
0   신규  23222
1   갱신   6425
2    -   2987

In [ ]:
# 계약구분과 종전계약 보증금(만원),	종전계약 월세(만원) 관계 분석

## 2. 서울 단독 다가구 매매

In [8]:
print("2021년 단독 다가구 매매")
display(df_deal2021.head())
print("2022년 단독 다가구 매매")
display(df_deal2022.head())
print("2023년 단독 다가구 매매")
display(df_deal2023.head())
print("2024년 단독 다가구 매매")
display(df_deal2024.head())

2021년 단독 다가구 매매

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 용산구 이태원동,3**,12m미만,30.00,월세,202112,31,500,55,1996.0,녹사평대로40나길,-,-,-,NaN,NaN,단독다가구
1,2,서울특별시 종로구 평창동,5**,8m미만,182.54,전세,202112,31,"70,000",0,2016.0,평창4길,202201~202401,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 용답동,8*,8m미만,28.00,월세,202112,31,"1,000",30,1990.0,용답29길,-,-,-,NaN,NaN,단독다가구
3,4,서울특별시 용산구 청파동2가,6*,8m미만,18.00,월세,202112,31,"1,000",45,1977.0,청파로47길,202202~202302,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 성동구 마장동,3**,8m미만,18.00,전세,202112,31,"13,000",0,2018.0,마조로14길,202201~202401,신규,-,NaN,NaN,단독다가구

2022년 단독 다가구 매매

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 용산구 후암동,1**,8m미만,15.90,월세,202212,31,500,40,NaN,두텁바위로1나길,202212~202412,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 종로구 명륜1가,3*,8m미만,18.15,월세,202212,31,"1,000",60,2010.0,혜화로5길,202301~202501,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 행당동,3*,8m미만,15.00,월세,202212,31,"4,000",40,1964.0,살곶이4길,202301~202501,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 중구 장충동2가,1**,8m미만,37.47,전세,202212,31,"18,500",0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 종로구 명륜3가,*,8m미만,42.00,전세,202212,31,"8,000",0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구

2023년 단독 다가구 매매

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,2**,8m미만,125.86,전세,202312,31,"10,000",0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,1*,8m미만,39.83,전세,202312,31,"9,200",0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 용답동,3*,12m미만,22.00,월세,202312,31,500,35,1993.0,용답25길,202401~202601,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 성동구 성수동1가,7*,12m미만,10.93,월세,202312,31,150,57,NaN,뚝섬로3길,202401~202412,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 용산구 용산동2가,*,8m미만,20.00,월세,202312,31,"1,000",30,1995.0,신흥로25가길,-,-,-,NaN,NaN,단독다가구

2024년 단독 다가구 매매

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 중구 황학동,1**,12m미만,24.00,월세,202412,31,400,40,1991.0,마장로3길,202501~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 행당동,3**,8m미만,42.00,전세,202412,31,"14,000",0,1998.0,마조로1길,202501~202701,갱신,-,"13,000",0.0,단독다가구
2,3,서울특별시 성동구 행당동,3**,12m미만,26.00,월세,202412,31,"3,000",70,NaN,행당로11길,202502~202702,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 성동구 옥수동,3**,8m미만,169.30,월세,202412,31,"1,000",80,1991.0,한림말3길,202501~202701,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 용산구 서계동,2**,8m미만,26.45,전세,202412,31,"3,000",0,1944.0,효창원로104라길,202501~202701,신규,-,NaN,NaN,단독다가구

In [9]:
# 단독 다가구 전월세
print("2021년 단독 다가구 전월세")
print(df_deal2021.info())
print("2022년 단독 다가구 전월세")
print(df_deal2022.info())
print("2023년 단독 다가구 전월세")
print(df_deal2023.info())
print("2024년 단독 다가구 전월세")
print(df_deal2024.info())

2021년 단독 다가구 전월세
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165988 entries, 0 to 165987
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            165988 non-null  int64
 1   시군구           165988 non-null  object
 2   번지            165965 non-null  object
 3   도로조건          165988 non-null  object
 4   계약면적(㎡)       165988 non-null  float64
 5   전월세구분         165988 non-null  object
 6   계약년월          165988 non-null  int64
 7   계약일           165988 non-null  int64
 8   보증금(만원)       165988 non-null  object
 9   월세금(만원)       165988 non-null  int64
 10  건축년도          156134 non-null  float64
 11  도로명           149332 non-null  object
 12  계약기간          165988 non-null  object
 13  계약구분          165988 non-null  object
 14  갱신요구권 사용      165988 non-null  object
 15  종전계약 보증금(만원)  7634 non-null    object
 16  종전계약 월세(만원)   7634 non-null    float64
 17  주택유형          165988 non-null  object
dtypes: float64(3), int64(4), object(11)
memory usage: 22.8+ MB
None
2022년 단독 다가구 전월세
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178466 entries, 0 to 178465
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            178466 non-null  int64
 1   시군구           178466 non-null  object
 2   번지            178452 non-null  object
 3   도로조건          178466 non-null  object
 4   계약면적(㎡)       178466 non-null  float64
 5   전월세구분         178466 non-null  object
 6   계약년월          178466 non-null  int64
 7   계약일           178466 non-null  int64
 8   보증금(만원)       178466 non-null  object
 9   월세금(만원)       178466 non-null  object
 10  건축년도          168541 non-null  float64
 11  도로명           163848 non-null  object
 12  계약기간          178466 non-null  object
 13  계약구분          178466 non-null  object
 14  갱신요구권 사용      178466 non-null  object
 15  종전계약 보증금(만원)  17340 non-null   object
 16  종전계약 월세(만원)   17340 non-null   float64
 17  주택유형          178466 non-null  object
dtypes: float64(3), int64(3), object(12)
memory usage: 24.5+ MB
None
2023년 단독 다가구 전월세
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154385 entries, 0 to 154384
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            154385 non-null  int64
 1   시군구           154385 non-null  object
 2   번지            154374 non-null  object
 3   도로조건          154385 non-null  object
 4   계약면적(㎡)       154385 non-null  float64
 5   전월세구분         154385 non-null  object
 6   계약년월          154385 non-null  int64
 7   계약일           154385 non-null  int64
 8   보증금(만원)       154385 non-null  object
 9   월세금(만원)       154385 non-null  object
 10  건축년도          143431 non-null  float64
 11  도로명           143360 non-null  object
 12  계약기간          154385 non-null  object
 13  계약구분          154385 non-null  object
 14  갱신요구권 사용      154385 non-null  object
 15  종전계약 보증금(만원)  14808 non-null   object
 16  종전계약 월세(만원)   14808 non-null   object
 17  주택유형          154385 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 21.2+ MB
None
2024년 단독 다가구 전월세
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141371 entries, 0 to 141370
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            141371 non-null  int64
 1   시군구           141371 non-null  object
 2   번지            141371 non-null  object
 3   도로조건          141371 non-null  object
 4   계약면적(㎡)       141371 non-null  float64
 5   전월세구분         141371 non-null  object
 6   계약년월          141371 non-null  int64
 7   계약일           141371 non-null  int64
 8   보증금(만원)       141371 non-null  object
 9   월세금(만원)       141371 non-null  object
 10  건축년도          120702 non-null  float64
 11  도로명           140333 non-null  object
 12  계약기간          141371 non-null  object
 13  계약구분          141371 non-null  object
 14  갱신요구권 사용      141371 non-null  object
 15  종전계약 보증금(만원)  14550 non-null   object
 16  종전계약 월세(만원)   14550 non-null   object
 17  주택유형          141371 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 19.4+ MB
None

In [10]:
# 데이터 모든 컬럼 동일함으로 '번지', '도로조건' 컬럼 제거
# '전월세구분'에서 전세만 추출
drop_columns = ['번지','도로조건']

# 컬럼 제거 및 필터링
def filtered_df(df):
    # 1. 번지, 도로 저건 제거
    df_deal_filtered = df.drop(columns = drop_columns, errors = 'ignore')

    # 2. 전월세구분 '전세'인 행만 추출
    df_deal_filtered = df_deal_filtered[df_deal_filtered['전월세구분'] == '전세']

    return df_deal_filtered.reset_index(drop = True)


# 3. 각 연도별 데이터셋 처리
df_deal2021_cleaned = filtered_df(df_deal2021)
df_deal2022_cleaned = filtered_df(df_deal2022)
df_deal2023_cleaned = filtered_df(df_deal2023)
df_deal2024_cleaned = filtered_df(df_deal2024)

print("2021년 단독 다가구 전세")
display(df_deal2021_cleaned)

print("2022년 단독 다가구 전세")
display(df_deal2022_cleaned)

print("2023년 단독 다가구 전세")
display(df_deal2023_cleaned)

print("2024년 단독 다가구 전세")
display(df_deal2024_cleaned)

2021년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 종로구 평창동,182.54,전세,202112,31,"70,000",0,2016.0,평창4길,202201~202401,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 성동구 마장동,18.00,전세,202112,31,"13,000",0,2018.0,마조로14길,202201~202401,신규,-,NaN,NaN,단독다가구
2,6,서울특별시 성동구 마장동,19.00,전세,202112,31,"10,000",0,1992.0,마조로12길,202202~202402,신규,-,NaN,NaN,단독다가구
3,7,서울특별시 용산구 이태원동,36.13,전세,202112,31,"25,000",0,1991.0,NaN,-,-,-,NaN,NaN,단독다가구
4,9,서울특별시 용산구 이태원동,36.13,전세,202112,31,"25,000",0,1991.0,이태원로16길,202202~202402,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65780,165975,서울특별시 금천구 독산동,54.00,전세,202101,1,"8,000",0,1991.0,독산로58가길,-,-,-,NaN,NaN,단독다가구
65781,165976,서울특별시 영등포구 신길동,23.00,전세,202101,1,"10,000",0,2017.0,도림로,-,-,-,NaN,NaN,단독다가구
65782,165978,서울특별시 중랑구 면목동,67.08,전세,202101,1,"8,500",0,1990.0,용마산로94길,-,-,-,NaN,NaN,단독다가구
65783,165987,서울특별시 중랑구 중화동,56.49,전세,202101,1,"17,000",0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구
65784,165988,서울특별시 중랑구 중화동,56.49,전세,202101,1,"17,000",0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구

2022년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,4,서울특별시 중구 장충동2가,37.47,전세,202212,31,"18,500",0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 종로구 명륜3가,42.00,전세,202212,31,"8,000",0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구
2,11,서울특별시 용산구 후암동,21.02,전세,202212,31,"6,300",0,1960.0,신흥로36길,202302~202502,갱신,사용,"6,000",0.0,단독다가구
3,19,서울특별시 용산구 보광동,36.29,전세,202212,31,"11,500",0,1995.0,우사단로4라길,202301~202501,신규,-,NaN,NaN,단독다가구
4,21,서울특별시 용산구 청파동2가,12.24,전세,202212,31,"7,000",0,1934.0,NaN,-,-,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55524,178457,서울특별시 금천구 가산동,56.62,전세,202201,1,"10,000",0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55525,178458,서울특별시 영등포구 당산동1가,16.50,전세,202201,1,"6,000",0,2015.0,당산로20길,-,-,-,NaN,NaN,단독다가구
55526,178459,서울특별시 금천구 가산동,56.62,전세,202201,1,"10,000",0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55527,178460,서울특별시 구로구 구로동,30.00,전세,202201,1,"8,000",0,2007.0,구로중앙로12길,202203~202403,신규,-,NaN,NaN,단독다가구
55528,178464,서울특별시 구로구 개봉동,132.00,전세,202201,1,"15,000",0,1993.0,고척로,202201~202501,갱신,-,"11,000",0.0,단독다가구

2023년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,125.86,전세,202312,31,"10,000",0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,39.83,전세,202312,31,"9,200",0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,9,서울특별시 광진구 구의동,21.00,전세,202312,31,"12,000",0,2001.0,아차산로49길,202402~202602,신규,-,NaN,NaN,단독다가구
3,12,서울특별시 중랑구 망우동,61.60,전세,202312,31,"14,600",0,2002.0,봉우재로53길,-,-,-,NaN,NaN,단독다가구
4,30,서울특별시 영등포구 대림동,26.00,전세,202312,31,"6,500",0,2010.0,도림로52길,202401~202601,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41231,154353,서울특별시 서대문구 홍제동,28.00,전세,202301,1,"15,600",0,NaN,NaN,-,-,-,NaN,NaN,단독다가구
41232,154359,서울특별시 성북구 하월곡동,16.00,전세,202301,1,"4,500",0,2013.0,월곡로18가길,-,-,-,NaN,NaN,단독다가구
41233,154368,서울특별시 동작구 신대방동,24.00,전세,202301,1,"3,500",0,1970.0,신대방6길,-,-,-,NaN,NaN,단독다가구
41234,154373,서울특별시 금천구 독산동,37.65,전세,202301,1,"9,000",0,1993.0,시흥대로90길,-,-,-,NaN,NaN,단독다가구
41235,154383,서울특별시 영등포구 당산동1가,42.70,전세,202301,1,"28,324",0,1970.0,영등포로29길,202301~202412,신규,-,NaN,NaN,단독다가구

2024년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 성동구 행당동,42.00,전세,202412,31,"14,000",0,1998.0,마조로1길,202501~202701,갱신,-,"13,000",0.0,단독다가구
1,5,서울특별시 용산구 서계동,26.45,전세,202412,31,"3,000",0,1944.0,효창원로104라길,202501~202701,신규,-,NaN,NaN,단독다가구
2,12,서울특별시 용산구 용산동2가,61.17,전세,202412,31,"25,000",0,1994.0,신흥로25가길,202502~202702,신규,-,NaN,NaN,단독다가구
3,19,서울특별시 광진구 중곡동,40.80,전세,202412,31,"11,000",0,1990.0,능동로43길,202502~202702,신규,-,NaN,NaN,단독다가구
4,22,서울특별시 성동구 성수동2가,50.00,전세,202412,31,"16,000",0,1995.0,성덕정길,202502~202702,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32629,141332,서울특별시 중랑구 망우동,36.00,전세,202401,1,"4,000",0,NaN,용마산로120길,202401~202812,신규,-,NaN,NaN,단독다가구
32630,141338,서울특별시 동작구 노량진동,50.00,전세,202401,1,"15,000",0,1970.0,장승배기로18가길,202401~202412,신규,-,NaN,NaN,단독다가구
32631,141349,서울특별시 서대문구 창천동,20.00,전세,202401,1,"10,000",0,2001.0,신촌로7길,202404~202602,신규,-,NaN,NaN,단독다가구
32632,141353,서울특별시 서대문구 남가좌동,18.00,전세,202401,1,"7,000",0,2017.0,증가로8길,202402~202501,신규,-,NaN,NaN,단독다가구
32633,141363,서울특별시 노원구 하계동,50.00,전세,202401,1,"10,000",0,1995.0,공릉로58길,202401~202612,갱신,-,"9,500",0.0,단독다가구

In [11]:
# 각 년도별 컬럼 결측값
display(pd.concat(
    [
        df_deal2021_cleaned.isnull().sum(),
        df_deal2022_cleaned.isnull().sum(),
        df_deal2023_cleaned.isnull().sum(),
        df_deal2024_cleaned.isnull().sum()
    ],
    axis=1,
    keys=['2021', '2022', '2023', '2024']
).reset_index().rename(columns={'index': 'column'}))

          column   2021   2022   2023   2024
0             NO      0      0      0      0
1            시군구      0      0      0      0
2        계약면적(㎡)      0      0      0      0
3          전월세구분      0      0      0      0
4           계약년월      0      0      0      0
5            계약일      0      0      0      0
6        보증금(만원)      0      0      0      0
7        월세금(만원)      0      0      0      0
8           건축년도   4675   3695   3280   5144
9            도로명   9978   7376   4649    401
10          계약기간      0      0      0      0
11          계약구분      0      0      0      0
12      갱신요구권 사용      0      0      0      0
13  종전계약 보증금(만원)  61029  45655  34146  26209
14   종전계약 월세(만원)  61029  45655  34146  26209
15          주택유형      0      0      0      0

In [23]:
# 보증금(만원), 월세금(만원) 데이터 타입 int로 변경

# 전처리 함수 정의
def clean_rent_columns(df):
    for col in ['보증금(만원)', '월세금(만원)']:
        df[col] = (
            df[col]
            .astype(str)               # 문자열로 변환
            .str.replace(',', '')      # 쉼표 제거
            .str.strip()               # 공백 제거
        )
        df[col] = pd.to_numeric(df[col], errors='coerce')  # 숫자로 변환, 오류시 NaN
        df[col] = df[col].fillna(0).astype(int)            # NaN은 0으로 대체 후 int
    return df

# 데이터프레임별로 처리
df_deal2021_cleaned = clean_rent_columns(df_deal2021_cleaned)
df_deal2022_cleaned = clean_rent_columns(df_deal2022_cleaned)
df_deal2023_cleaned = clean_rent_columns(df_deal2023_cleaned)
df_deal2024_cleaned = clean_rent_columns(df_deal2024_cleaned)

# 결과 확인
print("2021년 단독 다가구 전세")
display(df_deal2021_cleaned)

print("2022년 단독 다가구 전세")
display(df_deal2022_cleaned)

print("2023년 단독 다가구 전세")
display(df_deal2023_cleaned)

print("2024년 단독 다가구 전세")
display(df_deal2024_cleaned)

2021년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 종로구 평창동,182.54,전세,202112,31,70000,0,2016.0,평창4길,202201~202401,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 성동구 마장동,18.00,전세,202112,31,13000,0,2018.0,마조로14길,202201~202401,신규,-,NaN,NaN,단독다가구
2,6,서울특별시 성동구 마장동,19.00,전세,202112,31,10000,0,1992.0,마조로12길,202202~202402,신규,-,NaN,NaN,단독다가구
3,7,서울특별시 용산구 이태원동,36.13,전세,202112,31,25000,0,1991.0,NaN,-,-,-,NaN,NaN,단독다가구
4,9,서울특별시 용산구 이태원동,36.13,전세,202112,31,25000,0,1991.0,이태원로16길,202202~202402,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65780,165975,서울특별시 금천구 독산동,54.00,전세,202101,1,8000,0,1991.0,독산로58가길,-,-,-,NaN,NaN,단독다가구
65781,165976,서울특별시 영등포구 신길동,23.00,전세,202101,1,10000,0,2017.0,도림로,-,-,-,NaN,NaN,단독다가구
65782,165978,서울특별시 중랑구 면목동,67.08,전세,202101,1,8500,0,1990.0,용마산로94길,-,-,-,NaN,NaN,단독다가구
65783,165987,서울특별시 중랑구 중화동,56.49,전세,202101,1,17000,0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구
65784,165988,서울특별시 중랑구 중화동,56.49,전세,202101,1,17000,0,1992.0,봉화산로2길,-,-,-,NaN,NaN,단독다가구

2022년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,4,서울특별시 중구 장충동2가,37.47,전세,202212,31,18500,0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
1,5,서울특별시 종로구 명륜3가,42.00,전세,202212,31,8000,0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구
2,11,서울특별시 용산구 후암동,21.02,전세,202212,31,6300,0,1960.0,신흥로36길,202302~202502,갱신,사용,"6,000",0.0,단독다가구
3,19,서울특별시 용산구 보광동,36.29,전세,202212,31,11500,0,1995.0,우사단로4라길,202301~202501,신규,-,NaN,NaN,단독다가구
4,21,서울특별시 용산구 청파동2가,12.24,전세,202212,31,7000,0,1934.0,NaN,-,-,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55524,178457,서울특별시 금천구 가산동,56.62,전세,202201,1,10000,0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55525,178458,서울특별시 영등포구 당산동1가,16.50,전세,202201,1,6000,0,2015.0,당산로20길,-,-,-,NaN,NaN,단독다가구
55526,178459,서울특별시 금천구 가산동,56.62,전세,202201,1,10000,0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
55527,178460,서울특별시 구로구 구로동,30.00,전세,202201,1,8000,0,2007.0,구로중앙로12길,202203~202403,신규,-,NaN,NaN,단독다가구
55528,178464,서울특별시 구로구 개봉동,132.00,전세,202201,1,15000,0,1993.0,고척로,202201~202501,갱신,-,"11,000",0.0,단독다가구

2023년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,125.86,전세,202312,31,10000,0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,39.83,전세,202312,31,9200,0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,9,서울특별시 광진구 구의동,21.00,전세,202312,31,12000,0,2001.0,아차산로49길,202402~202602,신규,-,NaN,NaN,단독다가구
3,12,서울특별시 중랑구 망우동,61.60,전세,202312,31,14600,0,2002.0,봉우재로53길,-,-,-,NaN,NaN,단독다가구
4,30,서울특별시 영등포구 대림동,26.00,전세,202312,31,6500,0,2010.0,도림로52길,202401~202601,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41231,154353,서울특별시 서대문구 홍제동,28.00,전세,202301,1,15600,0,NaN,NaN,-,-,-,NaN,NaN,단독다가구
41232,154359,서울특별시 성북구 하월곡동,16.00,전세,202301,1,4500,0,2013.0,월곡로18가길,-,-,-,NaN,NaN,단독다가구
41233,154368,서울특별시 동작구 신대방동,24.00,전세,202301,1,3500,0,1970.0,신대방6길,-,-,-,NaN,NaN,단독다가구
41234,154373,서울특별시 금천구 독산동,37.65,전세,202301,1,9000,0,1993.0,시흥대로90길,-,-,-,NaN,NaN,단독다가구
41235,154383,서울특별시 영등포구 당산동1가,42.70,전세,202301,1,28324,0,1970.0,영등포로29길,202301~202412,신규,-,NaN,NaN,단독다가구

2024년 단독 다가구 전세

,NO,시군구,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,2,서울특별시 성동구 행당동,42.00,전세,202412,31,14000,0,1998.0,마조로1길,202501~202701,갱신,-,"13,000",0.0,단독다가구
1,5,서울특별시 용산구 서계동,26.45,전세,202412,31,3000,0,1944.0,효창원로104라길,202501~202701,신규,-,NaN,NaN,단독다가구
2,12,서울특별시 용산구 용산동2가,61.17,전세,202412,31,25000,0,1994.0,신흥로25가길,202502~202702,신규,-,NaN,NaN,단독다가구
3,19,서울특별시 광진구 중곡동,40.80,전세,202412,31,11000,0,1990.0,능동로43길,202502~202702,신규,-,NaN,NaN,단독다가구
4,22,서울특별시 성동구 성수동2가,50.00,전세,202412,31,16000,0,1995.0,성덕정길,202502~202702,신규,-,NaN,NaN,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32629,141332,서울특별시 중랑구 망우동,36.00,전세,202401,1,4000,0,NaN,용마산로120길,202401~202812,신규,-,NaN,NaN,단독다가구
32630,141338,서울특별시 동작구 노량진동,50.00,전세,202401,1,15000,0,1970.0,장승배기로18가길,202401~202412,신규,-,NaN,NaN,단독다가구
32631,141349,서울특별시 서대문구 창천동,20.00,전세,202401,1,10000,0,2001.0,신촌로7길,202404~202602,신규,-,NaN,NaN,단독다가구
32632,141353,서울특별시 서대문구 남가좌동,18.00,전세,202401,1,7000,0,2017.0,증가로8길,202402~202501,신규,-,NaN,NaN,단독다가구
32633,141363,서울특별시 노원구 하계동,50.00,전세,202401,1,10000,0,1995.0,공릉로58길,202401~202612,갱신,-,"9,500",0.0,단독다가구

In [24]:
print("2021년 단독 다가구 전세")
display(df_deal2021_cleaned['계약구분'].value_counts().reset_index())
print("2022년 단독 다가구 전세")
display(df_deal2022_cleaned['계약구분'].value_counts().reset_index())
print("2023년 단독 다가구 전세")
display(df_deal2023_cleaned['계약구분'].value_counts().reset_index())
print("2024년 단독 다가구 전세")
display(df_deal2024_cleaned['계약구분'].value_counts().reset_index())

2021년 단독 다가구 전세

  계약구분  count
0    -  43441
1   신규  17588
2   갱신   4756

2022년 단독 다가구 전세

  계약구분  count
0   신규  24842
1    -  20813
2   갱신   9874

2023년 단독 다가구 전세

  계약구분  count
0   신규  21359
1    -  12787
2   갱신   7090

2024년 단독 다가구 전세

  계약구분  count
0   신규  23222
1   갱신   6425
2    -   2987