In [1]:
import pandas as pd

In [12]:
df_2021 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)
df_2021.head()

C:\Users\rmagm\AppData\Local\Temp\ipykernel_23880\2884088367.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/서울특별시 단독,다가구 전월세 데이터/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 용산구 후암동,1**,8m미만,15.90,월세,202212,31,500,40,NaN,두텁바위로1나길,202212~202412,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 종로구 명륜1가,3*,8m미만,18.15,월세,202212,31,"1,000",60,2010.0,혜화로5길,202301~202501,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 행당동,3*,8m미만,15.00,월세,202212,31,"4,000",40,1964.0,살곶이4길,202301~202501,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 중구 장충동2가,1**,8m미만,37.47,전세,202212,31,"18,500",0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 종로구 명륜3가,*,8m미만,42.00,전세,202212,31,"8,000",0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구

In [13]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178466 entries, 0 to 178465
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            178466 non-null  int64
 1   시군구           178466 non-null  object
 2   번지            178452 non-null  object
 3   도로조건          178466 non-null  object
 4   계약면적(㎡)       178466 non-null  float64
 5   전월세구분         178466 non-null  object
 6   계약년월          178466 non-null  int64
 7   계약일           178466 non-null  int64
 8   보증금(만원)       178466 non-null  object
 9   월세금(만원)       178466 non-null  object
 10  건축년도          168541 non-null  float64
 11  도로명           163848 non-null  object
 12  계약기간          178466 non-null  object
 13  계약구분          178466 non-null  object
 14  갱신요구권 사용      178466 non-null  object
 15  종전계약 보증금(만원)  17340 non-null   object
 16  종전계약 월세(만원)   17340 non-null   float64
 17  주택유형          178466 non-null  object
dtypes: float64(3), int64(3), object(12)
memory usage: 24.5+ MB