In [1]:
import pandas as pd

In [6]:
df_2021 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/단독다가구/단독다가구(전월세)_실거래가_2021년.csv",  encoding='cp949', header=15)
df_2022 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/단독다가구/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)
df_2023 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/단독다가구/단독다가구(전월세)_실거래가_2023년.csv",  encoding='cp949', header=15)

df_2021.head()
df_2022.head()
df_2023.head()

C:\Users\rmagm\AppData\Local\Temp\ipykernel_4384\285794160.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/단독다가구/단독다가구(전월세)_실거래가_2022년.csv",  encoding='cp949', header=15)
C:\Users\rmagm\AppData\Local\Temp\ipykernel_4384\285794160.py:3: DtypeWarning: Columns (9,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv("C:/Users/rmagm/OneDrive/바탕 화면/vscode/단독다가구/단독다가구(전월세)_실거래가_2023년.csv",  encoding='cp949', header=15)

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,2**,8m미만,125.86,전세,202312,31,"10,000",0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,1*,8m미만,39.83,전세,202312,31,"9,200",0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 용답동,3*,12m미만,22.00,월세,202312,31,500,35,1993.0,용답25길,202401~202601,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 성동구 성수동1가,7*,12m미만,10.93,월세,202312,31,150,57,NaN,뚝섬로3길,202401~202412,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 용산구 용산동2가,*,8m미만,20.00,월세,202312,31,"1,000",30,1995.0,신흥로25가길,-,-,-,NaN,NaN,단독다가구

In [10]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165988 entries, 0 to 165987
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            165988 non-null  int64
 1   시군구           165988 non-null  object
 2   번지            165965 non-null  object
 3   도로조건          165988 non-null  object
 4   계약면적(㎡)       165988 non-null  float64
 5   전월세구분         165988 non-null  object
 6   계약년월          165988 non-null  int64
 7   계약일           165988 non-null  int64
 8   보증금(만원)       165988 non-null  object
 9   월세금(만원)       165988 non-null  int64
 10  건축년도          156134 non-null  float64
 11  도로명           149332 non-null  object
 12  계약기간          165988 non-null  object
 13  계약구분          165988 non-null  object
 14  갱신요구권 사용      165988 non-null  object
 15  종전계약 보증금(만원)  7634 non-null    object
 16  종전계약 월세(만원)   7634 non-null    float64
 17  주택유형          165988 non-null  object
dtypes: float64(3), int64(4), object(11)
memory usage: 22.8+ MB

In [9]:
df_2021.isnull().sum()

NO                   0
시군구                  0
번지                  23
도로조건                 0
계약면적(㎡)              0
전월세구분                0
계약년월                 0
계약일                  0
보증금(만원)              0
월세금(만원)              0
건축년도              9854
도로명              16656
계약기간                 0
계약구분                 0
갱신요구권 사용             0
종전계약 보증금(만원)    158354
종전계약 월세(만원)     158354
주택유형                 0
dtype: int64

In [15]:
df_2021['전월세구분'].value_counts()

전월세구분
월세    100203
전세     65785
Name: count, dtype: int64

In [19]:
df_2021['계약구분'].value_counts()

계약구분
-     98986
신규    59368
갱신     7634
Name: count, dtype: int64

In [35]:
a = df_2021[df_2021['종전계약 보증금(만원)'].notnull()]
a

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
26,27,서울특별시 성동구 성수동1가,6**,8m미만,49.50,월세,202112,31,700,60,1996.0,서울숲2길,202201~202301,갱신,-,700,58.0,단독다가구
27,28,서울특별시 성동구 성수동1가,7*,12m미만,10.70,월세,202112,31,150,55,2019.0,뚝섬로3길,202202~202207,갱신,-,150,57.0,단독다가구
46,47,서울특별시 중구 신당동,3**,8m미만,99.90,전세,202112,31,"32,000",0,1989.0,동호로11다길,202112~202312,갱신,-,"27,000",0.0,단독다가구
61,62,서울특별시 동대문구 제기동,2**,8m미만,80.40,전세,202112,31,"20,000",0,2003.0,약령시로5길,202202~202402,갱신,사용,"20,000",0.0,단독다가구
81,82,서울특별시 광진구 자양동,1*,8m미만,15.00,월세,202112,31,"2,000",40,1988.0,아차산로22길,-,갱신,-,"2,000",35.0,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164850,164851,서울특별시 노원구 공릉동,5**,8m미만,60.00,전세,202101,5,"19,500",0,NaN,동일로176길,202101~202401,갱신,-,"17,500",0.0,단독다가구
165046,165047,서울특별시 관악구 신림동,4**,8m미만,23.10,월세,202101,4,500,41,2017.0,문성로40길,202301~202501,갱신,-,500,41.0,단독다가구
165735,165736,서울특별시 중랑구 면목동,5**,8m미만,23.10,전세,202101,2,"15,000",0,2018.0,면목로65길,202103~202303,갱신,-,"15,000",0.0,단독다가구
165836,165837,서울특별시 영등포구 대림동,8**,8m미만,60.00,월세,202101,2,200,25,1986.0,가마산로31길,202101~202301,갱신,-,200,25.0,단독다가구
165916,165917,서울특별시 은평구 불광동,4**,8m미만,77.98,전세,202101,1,"13,000",0,1997.0,통일로92길,202101~202107,갱신,-,"13,000",0.0,단독다가구

In [36]:
a['종전계약 보증금(만원)'].isnull().sum()

np.int64(0)

In [37]:
a['계약구분'].value_counts()

계약구분
갱신    7634
Name: count, dtype: int64

In [7]:
df_2022.head()

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 용산구 후암동,1**,8m미만,15.90,월세,202212,31,500,40,NaN,두텁바위로1나길,202212~202412,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 종로구 명륜1가,3*,8m미만,18.15,월세,202212,31,"1,000",60,2010.0,혜화로5길,202301~202501,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 행당동,3*,8m미만,15.00,월세,202212,31,"4,000",40,1964.0,살곶이4길,202301~202501,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 중구 장충동2가,1**,8m미만,37.47,전세,202212,31,"18,500",0,2001.0,동호로28길,202301~202501,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 종로구 명륜3가,*,8m미만,42.00,전세,202212,31,"8,000",0,NaN,성균관로13길,202301~202501,신규,-,NaN,NaN,단독다가구

In [11]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178466 entries, 0 to 178465
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            178466 non-null  int64
 1   시군구           178466 non-null  object
 2   번지            178452 non-null  object
 3   도로조건          178466 non-null  object
 4   계약면적(㎡)       178466 non-null  float64
 5   전월세구분         178466 non-null  object
 6   계약년월          178466 non-null  int64
 7   계약일           178466 non-null  int64
 8   보증금(만원)       178466 non-null  object
 9   월세금(만원)       178466 non-null  object
 10  건축년도          168541 non-null  float64
 11  도로명           163848 non-null  object
 12  계약기간          178466 non-null  object
 13  계약구분          178466 non-null  object
 14  갱신요구권 사용      178466 non-null  object
 15  종전계약 보증금(만원)  17340 non-null   object
 16  종전계약 월세(만원)   17340 non-null   float64
 17  주택유형          178466 non-null  object
dtypes: float64(3), int64(3), object(12)
memory usage: 24.5+ MB

In [12]:
df_2022.isnull().sum()

NO                   0
시군구                  0
번지                  14
도로조건                 0
계약면적(㎡)              0
전월세구분                0
계약년월                 0
계약일                  0
보증금(만원)              0
월세금(만원)              0
건축년도              9925
도로명              14618
계약기간                 0
계약구분                 0
갱신요구권 사용             0
종전계약 보증금(만원)    161126
종전계약 월세(만원)     161126
주택유형                 0
dtype: int64

In [13]:
df_2022['전월세구분'].value_counts()

전월세구분
월세    122937
전세     55529
Name: count, dtype: int64

In [20]:
df_2022['계약구분'].value_counts()

계약구분
신규    109549
-      51577
갱신     17340
Name: count, dtype: int64

In [28]:
a = df_2022[df_2022['종전계약 보증금(만원)'].notnull()]
a

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
10,11,서울특별시 용산구 후암동,4**,8m미만,21.02,전세,202212,31,"6,300",0,1960.0,신흥로36길,202302~202502,갱신,사용,"6,000",0.0,단독다가구
12,13,서울특별시 종로구 숭인동,7*,8m미만,19.00,월세,202212,31,500,50,NaN,종로63길,202212~202312,갱신,-,500,40.0,단독다가구
17,18,서울특별시 종로구 숭인동,7*,8m미만,45.00,월세,202212,31,"9,500",17,NaN,종로63길,202212~202612,갱신,-,"9,500",17.0,단독다가구
27,28,서울특별시 용산구 이태원동,3**,8m미만,25.59,월세,202212,31,"12,000",20,1960.0,녹사평대로46길,202301~202501,갱신,-,"10,000",20.0,단독다가구
34,35,서울특별시 용산구 후암동,5*,8m미만,40.14,전세,202212,31,"13,650",0,2008.0,후암로28가길,202301~202501,갱신,-,"13,000",0.0,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178439,178440,서울특별시 도봉구 쌍문동,2**,12m미만,30.00,월세,202201,1,270,40,1990.0,우이천로38길,202201~202301,갱신,-,500,35.0,단독다가구
178441,178442,서울특별시 도봉구 방학동,6**,8m미만,25.00,월세,202201,1,320,35,1992.0,도봉로147길,202201~202312,갱신,-,500,35.0,단독다가구
178456,178457,서울특별시 금천구 가산동,8*,12m미만,56.62,전세,202201,1,"10,000",0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
178458,178459,서울특별시 금천구 가산동,8*,12m미만,56.62,전세,202201,1,"10,000",0,2002.0,벚꽃로38길,202201~202401,갱신,-,"20,000",0.0,단독다가구
178463,178464,서울특별시 구로구 개봉동,9*,8m미만,132.00,전세,202201,1,"15,000",0,1993.0,고척로,202201~202501,갱신,-,"11,000",0.0,단독다가구

In [27]:
a['종전계약 보증금(만원)'].isnull().sum()

np.int64(0)

In [29]:
a['계약구분'].value_counts()

계약구분
갱신    17340
Name: count, dtype: int64

In [8]:
df_2023.head()

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 종로구 신영동,2**,8m미만,125.86,전세,202312,31,"10,000",0,1969.0,세검정로7길,202401~202601,신규,-,NaN,NaN,단독다가구
1,2,서울특별시 성동구 성수동1가,1*,8m미만,39.83,전세,202312,31,"9,200",0,1990.0,상원10가길,202312~202512,신규,-,NaN,NaN,단독다가구
2,3,서울특별시 성동구 용답동,3*,12m미만,22.00,월세,202312,31,500,35,1993.0,용답25길,202401~202601,신규,-,NaN,NaN,단독다가구
3,4,서울특별시 성동구 성수동1가,7*,12m미만,10.93,월세,202312,31,150,57,NaN,뚝섬로3길,202401~202412,신규,-,NaN,NaN,단독다가구
4,5,서울특별시 용산구 용산동2가,*,8m미만,20.00,월세,202312,31,"1,000",30,1995.0,신흥로25가길,-,-,-,NaN,NaN,단독다가구

In [16]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154385 entries, 0 to 154384
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   NO            154385 non-null  int64
 1   시군구           154385 non-null  object
 2   번지            154374 non-null  object
 3   도로조건          154385 non-null  object
 4   계약면적(㎡)       154385 non-null  float64
 5   전월세구분         154385 non-null  object
 6   계약년월          154385 non-null  int64
 7   계약일           154385 non-null  int64
 8   보증금(만원)       154385 non-null  object
 9   월세금(만원)       154385 non-null  object
 10  건축년도          143431 non-null  float64
 11  도로명           143360 non-null  object
 12  계약기간          154385 non-null  object
 13  계약구분          154385 non-null  object
 14  갱신요구권 사용      154385 non-null  object
 15  종전계약 보증금(만원)  14808 non-null   object
 16  종전계약 월세(만원)   14808 non-null   object
 17  주택유형          154385 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 21.2+ MB

In [17]:
df_2023.isnull().sum()

NO                   0
시군구                  0
번지                  11
도로조건                 0
계약면적(㎡)              0
전월세구분                0
계약년월                 0
계약일                  0
보증금(만원)              0
월세금(만원)              0
건축년도             10954
도로명              11025
계약기간                 0
계약구분                 0
갱신요구권 사용             0
종전계약 보증금(만원)    139577
종전계약 월세(만원)     139577
주택유형                 0
dtype: int64

In [18]:
df_2023['전월세구분'].value_counts()

전월세구분
월세    113149
전세     41236
Name: count, dtype: int64

In [32]:
a = df_2023[df_2023['종전계약 보증금(만원)'].notnull()]
a

,NO,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세금(만원),건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
6,7,서울특별시 종로구 창신동,1**,12m미만,75.00,월세,202312,31,"1,000",80,NaN,창신6가길,202312~202503,갱신,-,"2,000",70.0,단독다가구
16,17,서울특별시 성북구 하월곡동,7*,25m미만,84.00,월세,202312,31,"10,000",35,1984.0,오패산로,202401~202601,갱신,-,"10,000",20.0,단독다가구
20,21,서울특별시 성북구 안암동5가,1**,8m미만,25.00,월세,202312,31,"1,000",68,2019.0,개운사1길,202401~202501,갱신,-,"1,000",65.0,단독다가구
67,68,서울특별시 관악구 봉천동,1***,8m미만,19.00,월세,202312,31,"3,000",50,2018.0,남부순환로247길,202402~202502,갱신,-,"10,000",20.0,단독다가구
69,70,서울특별시 서초구 잠원동,4*,12m미만,29.70,월세,202312,31,"1,000",45,1997.0,신반포로43길,202312~202512,갱신,-,"1,000",45.0,단독다가구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154349,154350,서울특별시 은평구 대조동,2**,8m미만,50.00,월세,202301,1,500,42,1995.0,통일로77길,202301~202506,갱신,-,500,42.0,단독다가구
154351,154352,서울특별시 은평구 갈현동,2**,8m미만,41.57,월세,202301,1,500,35,1993.0,갈현로37길,202301~202412,갱신,-,500,30.0,단독다가구
154368,154369,서울특별시 관악구 봉천동,6**,8m미만,125.00,월세,202301,1,"5,000",50,NaN,봉천로13길,202301~202501,갱신,-,"2,000",40.0,단독다가구
154376,154377,서울특별시 구로구 구로동,5**,8m미만,79.20,월세,202301,1,500,35,1988.0,구로중앙로32나길,202301~202412,갱신,-,500,37.0,단독다가구
154384,154385,서울특별시 금천구 독산동,9**,8m미만,17.00,월세,202301,1,"3,000",30,NaN,독산로103길,202307~202507,갱신,-,"1,000",34.0,단독다가구

In [31]:
a['종전계약 보증금(만원)'].isnull().sum()

np.int64(0)

In [33]:
a['계약구분'].value_counts()

계약구분
갱신    14808
Name: count, dtype: int64