In [1]:
import pandas as pd

In [2]:
import sys

In [3]:
print(sys.executable)

/Library/Developer/CommandLineTools/usr/bin/python3

In [4]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/minju/Library/Python/3.9/lib/python/site-packages (2.3.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/minju/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /Users/minju/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/minju/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/minju/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.1.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [6]:
df_2021_buy = pd.read_csv('/Users/minju/Desktop/project/연립다세대(매매)_실거래가_2021.csv', encoding='euc-kr', header=15)

In [7]:
df_2021_buy

,NO,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자
0,1,서울특별시 용산구 원효로1가,17-33,17,33,세종빌리지2차,50.46,22.6400,202112,31,"68,000",4,-,-,2007,백범로79다길 11,-,중개거래,서울 용산구,-
1,2,서울특별시 성동구 도선동,329-1,329,1,에코하우스(1동),12.25,6.5300,202112,31,"13,000",6,-,-,2011,무학로6길 18-1,-,중개거래,서울 성동구,-
2,3,서울특별시 중랑구 망우동,514-2,514,2,현대아트빌,29.18,22.5441,202112,31,"30,500",3,-,-,2017,상봉로26길 50,-,중개거래,서울 중랑구,-
3,4,서울특별시 성동구 홍익동,17-3,17,3,레이나D동,55.06,34.0300,202112,31,"59,000",3,-,-,2014,마장로23길 6-15,-,중개거래,서울 성동구,-
4,5,서울특별시 강북구 번동,437-78,437,78,진주8동,41.04,34.1000,202112,31,"31,000",2,-,-,1987,덕릉로40가길 25-5,-,중개거래,서울 동대문구,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60699,60700,서울특별시 영등포구 대림동,844-18,844,18,동서빌라(844-18),50.75,32.8500,202101,1,"20,000",2,-,-,1994,도림로50길 9-5,-,-,-,-
60700,60701,서울특별시 구로구 궁동,283-11,283,11,인화빌라(283-11),36.98,23.3600,202101,1,"13,000",3,-,-,1994,오리로17길 62,-,-,-,-
60701,60702,서울특별시 구로구 구로동,797-27,797,27,(797-27),43.16,13.7000,202101,1,"20,000",3,-,-,1996,도림로6길 30-5,-,-,-,-
60702,60703,서울특별시 영등포구 대림동,993-4,993,4,"현대그린빌라A,B동",72.72,48.2000,202101,1,"48,000",2,-,-,1986,시흥대로175가길 1,-,-,-,-
60703,60704,서울특별시 강서구 등촌동,647-68,647,68,이건하우스,47.94,30.9306,202101,1,"27,300",5,-,-,2012,공항대로59나길 30,-,-,-,-

In [8]:
df_2021_buy.isnull().sum()

NO          0
시군구         0
번지          0
본번          0
부번          0
건물명         0
전용면적(㎡)     0
대지권면적(㎡)    0
계약년월        0
계약일         0
거래금액(만원)    0
층           0
매수자         0
매도자         0
건축년도        0
도로명         0
해제사유발생일     0
거래유형        0
중개사소재지      0
등기일자        0
dtype: int64

In [9]:
df_2021_buy['계약년월'].min(), df_2021_buy['계약년월'].max()

(np.int64(202101), np.int64(202112))

In [10]:
df_2021_buy.sort_values(by='계약년월',ascending=True)

,NO,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자
60703,60704,서울특별시 강서구 등촌동,647-68,647,68,이건하우스,47.94,30.9306,202101,1,"27,300",5,-,-,2012,공항대로59나길 30,-,-,-,-
56481,56482,서울특별시 강동구 천호동,220-11,220,11,경원쉐르빌,44.88,25.6432,202101,23,"28,500",2,-,-,2015,구천면로42길 28-26,-,-,-,-
56482,56483,서울특별시 강동구 천호동,25-36,25,36,예가풍경채,42.05,28.4200,202101,23,"35,000",5,-,-,2015,양재대로135길 4-15,-,-,-,-
56483,56484,서울특별시 강동구 천호동,337-3,337,3,하우징허브바람개비1,30.40,22.1000,202101,23,"27,000",5,-,-,2017,천중로2길 35-5,-,-,-,-
56484,56485,서울특별시 송파구 마천동,200-23,200,23,(200-23),34.23,25.0000,202101,23,"65,000",3,-,-,2006,성내천로 268,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2384,2385,서울특별시 서초구 양재동,123-2,123,2,금성빌라,69.30,27.2300,202112,11,"33,800",-1,-,-,1993,양재천로19길 11-9,-,중개거래,서울 서초구,-
2383,2384,서울특별시 서초구 양재동,383-6,383,6,다인빌리지,76.44,44.2800,202112,11,"80,000",2,-,-,1997,동산로12길 54,-,중개거래,서울 서초구,-
2382,2383,서울특별시 서초구 양재동,386-24,386,24,동산마루빌102동,55.73,35.9700,202112,11,"45,000",2,-,-,2006,논현로1길 62,-,직거래,-,-
2688,2689,서울특별시 마포구 연남동,487-432,487,432,오네스타,48.24,30.8000,202112,9,"53,800",3,-,-,2021,성미산로17길 112-1,-,직거래,-,-
0,1,서울특별시 용산구 원효로1가,17-33,17,33,세종빌리지2차,50.46,22.6400,202112,31,"68,000",4,-,-,2007,백범로79다길 11,-,중개거래,서울 용산구,-

In [11]:
df_2021_buy.duplicated().sum()

np.int64(0)

In [12]:
df_2021_buy.dtypes

NO            int64
시군구          object
번지           object
본번            int64
부번            int64
건물명          object
전용면적(㎡)     float64
대지권면적(㎡)    float64
계약년월          int64
계약일           int64
거래금액(만원)     object
층             int64
매수자          object
매도자          object
건축년도          int64
도로명          object
해제사유발생일      object
거래유형         object
중개사소재지       object
등기일자         object
dtype: object

In [13]:
df_2021_buy.sort_values(by='계약년월',ascending=True)

,NO,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자
60703,60704,서울특별시 강서구 등촌동,647-68,647,68,이건하우스,47.94,30.9306,202101,1,"27,300",5,-,-,2012,공항대로59나길 30,-,-,-,-
56481,56482,서울특별시 강동구 천호동,220-11,220,11,경원쉐르빌,44.88,25.6432,202101,23,"28,500",2,-,-,2015,구천면로42길 28-26,-,-,-,-
56482,56483,서울특별시 강동구 천호동,25-36,25,36,예가풍경채,42.05,28.4200,202101,23,"35,000",5,-,-,2015,양재대로135길 4-15,-,-,-,-
56483,56484,서울특별시 강동구 천호동,337-3,337,3,하우징허브바람개비1,30.40,22.1000,202101,23,"27,000",5,-,-,2017,천중로2길 35-5,-,-,-,-
56484,56485,서울특별시 송파구 마천동,200-23,200,23,(200-23),34.23,25.0000,202101,23,"65,000",3,-,-,2006,성내천로 268,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2384,2385,서울특별시 서초구 양재동,123-2,123,2,금성빌라,69.30,27.2300,202112,11,"33,800",-1,-,-,1993,양재천로19길 11-9,-,중개거래,서울 서초구,-
2383,2384,서울특별시 서초구 양재동,383-6,383,6,다인빌리지,76.44,44.2800,202112,11,"80,000",2,-,-,1997,동산로12길 54,-,중개거래,서울 서초구,-
2382,2383,서울특별시 서초구 양재동,386-24,386,24,동산마루빌102동,55.73,35.9700,202112,11,"45,000",2,-,-,2006,논현로1길 62,-,직거래,-,-
2688,2689,서울특별시 마포구 연남동,487-432,487,432,오네스타,48.24,30.8000,202112,9,"53,800",3,-,-,2021,성미산로17길 112-1,-,직거래,-,-
0,1,서울특별시 용산구 원효로1가,17-33,17,33,세종빌리지2차,50.46,22.6400,202112,31,"68,000",4,-,-,2007,백범로79다길 11,-,중개거래,서울 용산구,-

뭐야

In [14]:
df_2021_buy.columns

Index(['NO', '시군구', '번지', '본번', '부번', '건물명', '전용면적(㎡)', '대지권면적(㎡)', '계약년월',
       '계약일', '거래금액(만원)', '층', '매수자', '매도자', '건축년도', '도로명', '해제사유발생일', '거래유형',
       '중개사소재지', '등기일자'],
      dtype='object')

In [16]:
df_2021_buy.drop_duplicates(inplace=True)